# Generated by Django 6.0.3 on 2026-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Calm', 'Calm'), ('Neutral', 'Neutral'), ('Stressed', 'Stressed'), ('Angry', 'Angry'), ('Excited', 'Excited')], max_length=20),
        ),
    ]
